
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const GET_SIGNLE_POST_REQUEST = 'GET_SIGNLE_POST_REQUEST';
export const GET_SIGNLE_POST_SUCCESS = 'GET_SIGNLE_POST_SUCCESS';
export const GET_SIGNLE_POST_FAILURE = 'GET_SIGNLE_POST_FAILURE';

export const GET_USER_POSTS_REQUEST = 'GET_USER_POSTS_REQUEST';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_FAILURE = 'GET_USER_POSTS_FAILURE';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE';



export const GET_POST_COMMENTS_REQUEST = 'GET_POST_COMMENTS_REQUEST';
export const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS';
export const GET_POST_COMMENTS_FAILURE = 'GET_POST_COMMENTS_FAILURE';

export const CREATE_POST_COMMENT_REQUEST = 'CREATE_POST_COMMENT_REQUEST';
export const CREATE_POST_COMMENT_SUCCESS = 'CREATE_POST_COMMENT_SUCCESS';
export const CREATE_POST_COMMENT_FAILURE = 'CREATE_POST_COMMENT_FAILURE';

export const DELETE_POST_COMMENT_REQUEST = 'DELETE_POST_COMMENT_REQUEST';
export const DELETE_POST_COMMENT_SUCCESS = 'DELETE_POST_COMMENT_SUCCESS';
export const DELETE_POST_COMMENT_FAILURE = 'DELETE_POST_COMMENT_FAILURE';

export const LIKE_POST_COMMENT_REQUEST = 'LIKE_POST_COMMENT_REQUEST';
export const LIKE_POST_COMMENT_SUCCESS = 'LIKE_POST_COMMENT_SUCCESS';
export const LIKE_POST_COMMENT_FAILURE = 'LIKE_POST_COMMENT_FAILURE';

export const CLEAR_POST_COMMENTS = 'CLEAR_POST_COMMENTS';

export const SAVED_POST_REQUEST = 'SAVED_POST_REQUEST';
export const SAVED_POST_SUCCESS = 'SAVED_POST_SUCCESS';
export const SAVED_POST_FAILURE = 'SAVED_POST_FAILURE';




